version: '3.9'
services:
  db:
    image: postgres
    environment:
        PPOSTGRES_USER: postgres
        PPOSTGRES_PASSWORD: postgres123
        POSTGRES_DB: survey_db
        POSTGRES_HOST_AUTH_METHOD: "trust"

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      SURVEY_DATABASE_PASSWORD: postgres123
    depends_on:
      - db
    ports:
      - "3000:3000"
